### ISSUE TITLE
Tries to get keys of null

### ISSUE THREAD

**Issue by marineloken** [MathiasFrost/SimpleStores#1]
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Function.initializeDates (index.module.js:82:1)
    at SessionStore.get (index.module.js:203:1)
    at new AuthService (authService.ts:79:1)
    at ../dist/index.modern.js (authStore.ts:5:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.tsx (bundle.js:17:79)
    at options.factory (react refresh:6:1)
```

**Comment by marineloken** [comment]
fixed
